#log setting
logging:
  level:
    root: DEBUG


#email url
email:
  config:
    baseUrl: "http://localhost:8080"

spring:
  config:
    activate:
      on-profile: dev

  #static 파일을 개발할때 서버 재시작하지 않고 수정한 내용 반영
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false

  redis:
    host: redis
    port: 6379

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/swchat
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/suchat
    username: suchat_user
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true