#log setting
logging:
  level:
    com:
      USWRandomChat:
        backend: debug

spring:
  config:
    activate:
      on-profile: dev

  #static 파일을 개발할때 서버 재시작하지 않고 수정한 내용 반영
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/swchat
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true