server:
  port: 8080

spring:

  #  smtp
  mail:
    host: smtp.gmail.com
    port: 587
    username: nkdy50315031@gmail.com
    password: zczxsylqqelzckrq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

    # Redis 설정 추가
  redis:
    host: localhost
    port: 6379
    #password: 'redis6379'
  # profiles:
  #   active: local

logging.level:
  org.hibernate.SQL: debug
#  p6spygotj
#  org.hibernate.type: trace

#jwt.secret.key 값
jwt:
  secret:
    key: FC7DEE6E587E7E7EDE7A8E7DEEE6E6EF7E6DE7E7E6E76E7E6E6E7E76E6DEEF7